# Generated by Django 3.0.8 on 2020-07-17 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('installation_date', models.DateTimeField()),
                ('expected_lifetime', models.DurationField()),
                ('hardware_type', models.CharField(choices=[('SRV', 'Server'), ('RTR', 'Router'), ('SW', 'Switch'), ('FWL', 'Firewall'), ('WS', 'Work Station')], default='SRV', max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('installation_date', models.DateTimeField()),
                ('expected_lifetime', models.DurationField()),
                ('software_type', models.CharField(choices=[('OS', 'Operating System'), ('AV', 'AntiVirus'), ('MAIL', 'Email Server')], default='OS', max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
