# Generated by Django 3.0.8 on 2020-07-17 21:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 21, 4, 41, 223123, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='software',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 21, 4, 41, 223123, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='installation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 21, 4, 41, 223074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='software',
            name='installation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 21, 4, 41, 223074, tzinfo=utc)),
        ),
    ]
