# Generated by Django 3.0.8 on 2020-07-17 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20200717_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='installation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='software',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='software',
            name='installation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
