# Generated by Django 3.1.1 on 2020-10-02 11:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20200717_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_type', models.CharField(default='APL', max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('fqdn', models.URLField()),
                ('virt_phys', models.CharField(default='PHYS', max_length=4)),
                ('operating_system', models.CharField(default='LINUX', max_length=4)),
                ('license_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_of_life', models.DateTimeField(default=django.utils.timezone.now)),
                ('entite_responsable', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('environment', models.CharField(default='PROD', max_length=4)),
                ('ship_to_prod_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('poste_occupe', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SupportContract',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('support_provider', models.CharField(max_length=100)),
                ('contract_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contract_duration', models.DurationField()),
            ],
        ),
        migrations.DeleteModel(
            name='Hardware',
        ),
        migrations.RemoveField(
            model_name='software',
            name='expected_lifetime',
        ),
        migrations.RemoveField(
            model_name='software',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='software',
            name='installation_date',
        ),
        migrations.RemoveField(
            model_name='software',
            name='software_type',
        ),
        migrations.AddField(
            model_name='software',
            name='database_sever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.software'),
        ),
        migrations.AddField(
            model_name='software',
            name='environment',
            field=models.CharField(default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='software',
            name='ship_to_prod_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='equipment',
            name='referent_technique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.person'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='support',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.supportcontract'),
        ),
        migrations.AddField(
            model_name='software',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.equipment'),
        ),
        migrations.AddField(
            model_name='software',
            name='referent_technique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.person'),
        ),
    ]
