# Generated by Django 3.1.1 on 2020-10-02 14:00

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20201002_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSLCert',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='supportcontract',
            name='contract_duration',
        ),
        migrations.AddField(
            model_name='supportcontract',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('PRE', 'Pre-production'), ('DEV', 'Development')], default='PROD', max_length=4),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('SRV', 'Server'), ('RTR', 'Router'), ('SW', 'Switch'), ('FWL', 'Firewall'), ('APL', 'Appliance'), ('OTHER', 'Other')], default='APL', max_length=5),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='operating_system',
            field=models.CharField(choices=[('WIN', 'Windows'), ('LINUX', 'Linux'), ('BSD', 'BSD'), ('IOS', 'CISCO IOS')], default='LINUX', max_length=5),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='virt_phys',
            field=models.CharField(choices=[('VIRT', 'Virtual'), ('PHYS', 'Physical')], default='PHYS', max_length=4),
        ),
        migrations.AlterField(
            model_name='software',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('PRE', 'Pre-production'), ('DEV', 'Development')], default='PROD', max_length=4),
        ),
    ]
