# Generated by Django 3.1.1 on 2020-10-02 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20201002_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='end_of_life',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='license_end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='ship_to_prod_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='software',
            name='ship_to_prod_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sslcert',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='supportcontract',
            name='contract_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='supportcontract',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
