# Generated by Django 3.1.1 on 2020-10-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20201002_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='documentation',
            field=models.FileField(null=True, upload_to='Documentation/Equipment/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='software',
            name='documentation',
            field=models.FileField(null=True, upload_to='Documentation/Software/%Y/%m/%d'),
        ),
    ]
