# Generated by Django 3.1.2 on 2020-10-09 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20201003_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['license_end']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('last_name', 'first_name')},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['-ship_to_prod_date']},
        ),
        migrations.AlterModelOptions(
            name='sslcert',
            options={'ordering': ['expiration_date']},
        ),
        migrations.AlterModelOptions(
            name='supportcontract',
            options={'ordering': ['expiration_date']},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='documentation',
            field=models.FileField(blank=True, null=True, upload_to='Documentation/Equipment/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='referent_technique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.person'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.supportcontract'),
        ),
        migrations.AlterField(
            model_name='software',
            name='database_sever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.software'),
        ),
        migrations.AlterField(
            model_name='software',
            name='documentation',
            field=models.FileField(blank=True, null=True, upload_to='Documentation/Software/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='software',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.equipment'),
        ),
        migrations.AlterField(
            model_name='software',
            name='referent_technique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.person'),
        ),
    ]
