# Generated by Django 3.1.2 on 2020-10-20 13:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20201020_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentations',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(blank=True, null=True, upload_to='Documentation')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.equipment')),
            ],
        ),
    ]
