# Generated by Django 3.1.2 on 2020-10-21 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_documentations'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationMany',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documentation', models.FileField(blank=True, null=True, upload_to='Documentation')),
            ],
        ),
        migrations.RenameModel(
            old_name='Documentations',
            new_name='DocumentationsForeign',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='docs',
        ),
        migrations.DeleteModel(
            name='Documentation',
        ),
        migrations.AddField(
            model_name='equipment',
            name='documentation_many',
            field=models.ManyToManyField(to='manager.DocumentationMany'),
        ),
    ]
