# Generated by Django 3.1.2 on 2020-10-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20201021_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='documentation_many',
            field=models.ManyToManyField(blank=True, to='manager.DocumentationMany'),
        ),
    ]
