# Generated by Django 3.1.2 on 2020-10-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_auto_20201022_0935'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentationsEquipment',
            new_name='EquipmentDocumentation',
        ),
        migrations.RenameModel(
            old_name='DocumentationsSoftware',
            new_name='SoftwareDocumentation',
        ),
    ]
