# Generated by Django 3.1.2 on 2020-10-22 11:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_auto_20201022_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationmany',
            name='documentation',
            field=models.FileField(blank=True, null=True, upload_to='Documentation/many'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='end_of_life',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='license_end',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.supportcontract'),
        ),
    ]
